# Generated by Django 5.0.7 on 2025-08-22 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=25)),
                ('correo', models.CharField(max_length=128)),
                ('clave', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
